[package]
name = "mini-prolog"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
clap = "2.33"
lalrpop-util = "0.19.6"
regex = "1"